In [1]:
import pandas as pd
import numpy as np

In [2]:
def f_card_names():
#'''Create pandas.DataFrame object with deck'''
    # names for deck cards
    color = ['red', 'black']
    suit_red = ['diamonds', 'hearts']
    suit_black = ['spades', 'clubs' ]
    suit = [suit_red, suit_black]
    joker = 'Joker'
    pack = ['Ace', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'Jack', 'Queen', 'King']
    deck = []
    i = 0
    j = 53
    for clr in color:
       deck.append([j, clr, None, joker])
       j += 1
       for st in suit:
           if st is suit_red:
               for st_r in suit_red:
                   for card in pack:
                       i += 1
                       deck.append([i, clr, st_r, card])
    df = pd.DataFrame(deck, columns=['index', 'color', 'suit', 'card'])
    df.set_index('index', inplace=True)
    df.sort_index(inplace=True)
    return df

In [3]:
def f_card_value_by_name(card):
    """Allow get possible value from card
       input: Pandas.Series form DataFrame created by f_card_names
       return: tuple (value1, value2, win)
           value1 if card is number or picture
           value2 used if card is Ace
           win 1 if card was Joker
       except: if card not found return tuple(-1., -1., -1.)
    """
    
    values = {'Joker':12., 'Ace':1., 'Jack':10., 'Queen':10., 'King':10., '10':10., '9':9.,
              '8':8., '7':7., '6':6., '5':5., '4':4., '3':3., '2':2.}    
    try:
        return values[card]
    except:
        return -1.

In [4]:
def f_hand_over_cards(d):
    if d.size >= 4:
        player = d[:2]
        croupier = d[2:4]
        d = d[4:]
        return d, player, croupier
    else:
        print('Not enough cards in deck!')
        return d, [], []

In [5]:
def f_cards_values(cards_in_hand):
    vls = []
    cards = cards_names.iloc[cards_in_hand]
    #print(cards)
    for card in cards['card']:
        #print(card)
        vls.append(f_card_value_by_name(card)) 
    return vls

In [6]:
def f_more_card(d, p):
    if d.size >= 1:
        p = np.append(p, d[0])
        d = d[1:]
        return d, p
    else:
        print('Not enough cards in deck!')
        return None, None

In [7]:
def f_result(crds):
    print(crds)
    vals = np.array(f_cards_values(crds))
    print(vals)
    print()
    summ = 0.0
    res = 'continue'
    
    for v in vals:
        #Joker autowin
        if v == 12.:
            res = 'win'
            return 21., res
        #if Ace try to add 11
        if v == 1.:
            tmp = np.sum(vals) + 10.
            if tmp == 21.:
                res = 'win' 
                return tmp, res
            if tmp < 21.:
                res = 'continue' 
                return tmp, res
    
    summ = np.sum(vals)
    if summ < 21.:
        res = 'continue' 
        return summ, res
    if summ == 21.:
        res = 'win' 
        return summ, res
    else:
        res = 'lose' 
        return summ, res
        
    return summ, res

In [8]:
def f_new_deck(num_of_decks = 1):
    deck = np.arange(1, 54)
    if num_of_decks > 1:
        for i in np.arange(num_of_decks):
            np.append(deck, deck)
    np.random.shuffle(deck)
    dp = np.zeros(53*num_of_decks) 
    return deck, dp

In [9]:
cards_names = f_card_names()
#cards_names

In [10]:
deck, discard_pile = f_new_deck(1)
deck

array([44, 33, 25, 53,  2, 41, 39, 18, 11, 12, 51, 50, 30, 21, 15, 27, 10,
       29, 13, 20, 49, 19, 17,  1, 24, 32,  9,  5, 34, 22, 31,  3, 43, 37,
       28, 40, 16, 45, 48, 26,  7, 14, 42,  6, 36, 46, 23, 35,  8, 38, 52,
        4, 47])

In [11]:
deck, player, croupier = f_hand_over_cards(deck)
print('player')
print(cards_names.iloc[player])
f_result(player)

player
       color      suit card
index                      
45     black    hearts    6
34     black  diamonds    8
[44 33]
[6. 8.]



(14.0, 'continue')

In [12]:
deck, player = f_more_card(deck, player)
print(cards_names.iloc[player])
f_result(player)

       color      suit card
index                      
45     black    hearts    6
34     black  diamonds    8
3        red  diamonds    3
[44 33  2]
[6. 8. 3.]



(17.0, 'continue')

In [13]:
print('croupier')
print(cards_names.iloc[croupier])
f_result(croupier)

croupier
       color    suit   card
index                      
26       red  hearts   King
54     black    None  Joker
[25 53]
[10. 12.]



(21.0, 'win')

In [14]:
deck, croupier = f_more_card(deck, croupier)
print(cards_names.iloc[croupier])
f_result(croupier)

       color    suit   card
index                      
26       red  hearts   King
54     black    None  Joker
42     black  hearts      3
[25 53 41]
[10. 12.  3.]



(21.0, 'win')

In [ ]:
def f_check(p, c):
    