In [4]:
import numpy as np
import array
L = np.array(range(10))
L

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.array([3.14,4,2,3], dtype = 'float32')

array([3.14, 4.  , 2.  , 3.  ], dtype=float32)

In [15]:
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [16]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
np.full((3,5),3.14,dtype=int)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [21]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
np.random.random((3,3))

array([[0.76724551, 0.01299523, 0.27401421],
       [0.52311552, 0.02715656, 0.38338485],
       [0.39610399, 0.48655709, 0.073173  ]])

In [25]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [26]:
np.random.randint(0,10,(5,5))

array([[2, 9, 7, 4, 3],
       [9, 9, 6, 4, 1],
       [6, 0, 5, 0, 6],
       [6, 2, 8, 5, 2],
       [1, 8, 2, 2, 6]])

In [27]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
np.empty(3)

array([0., 0., 0.])

In [7]:
x1=np.random.randint(10,size=5)
x2=np.random.randint(10,size=(3,5))
x3=np.random.randint(10,size=(3,4,5))

In [8]:
print("x3 ndim:",x3.ndim)
print("x3 shape:",x3.shape)
print("x3 size:",x3.size)
print("x3 dtype:",x3.dtype)
print("x3 itemsize:",x3.itemsize, "bytes")
print("x3 nbytes",x3.nbytes)

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60
x3 dtype: int32
x3 itemsize: 4 bytes
x3 nbytes 240


In [9]:
x2

array([[4, 1, 2, 1, 8],
       [8, 6, 2, 8, 9],
       [6, 4, 2, 4, 9]])

In [10]:
x2[0,0]

4

In [11]:
x2[-1,-1]

9

In [12]:
x2[-1,-1] = 12
x2

array([[ 4,  1,  2,  1,  8],
       [ 8,  6,  2,  8,  9],
       [ 6,  4,  2,  4, 12]])

In [13]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
x[:5]

array([0, 1, 2, 3, 4])

In [15]:
x[5:]

array([5, 6, 7, 8, 9])

In [16]:
x[4:7]

array([4, 5, 6])

In [17]:
x[::2]

array([0, 2, 4, 6, 8])

In [18]:
x[1::2]

array([1, 3, 5, 7, 9])

In [19]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [20]:
x[2:9:3]

array([2, 5, 8])

In [21]:
x[6::-2]

array([6, 4, 2, 0])

In [22]:
x2

array([[ 4,  1,  2,  1,  8],
       [ 8,  6,  2,  8,  9],
       [ 6,  4,  2,  4, 12]])

In [23]:
x2[:2,:3]

array([[4, 1, 2],
       [8, 6, 2]])

In [24]:
x2[:3,::2]

array([[ 4,  2,  8],
       [ 8,  2,  9],
       [ 6,  2, 12]])

In [25]:
print(x2[:,0])

[4 8 6]


In [26]:
print(x2)

[[ 4  1  2  1  8]
 [ 8  6  2  8  9]
 [ 6  4  2  4 12]]


In [29]:
x2_sub = x2[:2,:2]
x2_sub

array([[4, 1],
       [8, 6]])

In [33]:
x2_sub[0,0] = 99
print(x2_sub)
print(x2)

[[99  1]
 [ 8  6]]
[[99  1  2  1  8]
 [ 8  6  2  8  9]
 [ 6  4  2  4 12]]


In [35]:
x2_sub_copy=x2[:2,:2].copy()
print(x2_sub_copy)
x2_sub_copy[0,0]=42
print(x2_sub_copy)
print(x2)

[[99  1]
 [ 8  6]]
[[42  1]
 [ 8  6]]
[[99  1  2  1  8]
 [ 8  6  2  8  9]
 [ 6  4  2  4 12]]


In [37]:
grid = np.arange(1,10).reshape((3,3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [38]:
xx = np.array([1,2,3])
print(xx)

[1 2 3]


In [40]:
xx[np.newaxis,:]

array([[1, 2, 3]])

In [42]:
xx.reshape(3,1)

array([[1],
       [2],
       [3]])

In [44]:
xx[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [46]:
x=np.array([1,2,3])
y=np.array([4,5,6])
np.concatenate([x,y])


array([1, 2, 3, 4, 5, 6])

In [48]:
grid = np.array([[1,2,3],
                [4,5,6]])
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [49]:
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])