In [1]:
import numpy as np
a=np.array([0,1,2])
b=np.array([5,5,5])
a+b

array([5, 6, 7])

In [2]:
a+5

array([5, 6, 7])

In [3]:
M=np.ones((3,3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [4]:
M+a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [5]:
a=np.arange(3)
b=np.arange(3)[:,np.newaxis]
print(a)
print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [6]:
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [7]:
x=np.random.random((10,3))
x

array([[0.33147046, 0.44433043, 0.53443926],
       [0.65101945, 0.50431911, 0.62062443],
       [0.75303654, 0.0967944 , 0.73783103],
       [0.68208682, 0.95742013, 0.06842684],
       [0.56581734, 0.24906388, 0.63719989],
       [0.2956059 , 0.07589147, 0.04566185],
       [0.88103959, 0.38876846, 0.24621702],
       [0.75182515, 0.42862392, 0.89071147],
       [0.95845282, 0.88276974, 0.89239188],
       [0.67534264, 0.09830946, 0.5119696 ]])

In [8]:
xmean=x.mean(0)
xmean


array([0.65456967, 0.4126291 , 0.51854733])

In [9]:
x_centered=x-xmean
x_centered.mean(0)

array([-2.22044605e-17,  2.77555756e-17,  1.11022302e-17])